- name: "Close port"
  become: yes
  firewalld:
    port: '{{ firewalld_port }}'
    state: disabled 
    permanent: true

- name: Restart firewalld 
  become: yes
  systemd:
    name: firewalld
    state: restarted

- name: Wait for system to become reachable
  wait_for_connection:
